# -*- coding: utf-8 -*-
"""Inference_RICOSCREEN2WORDS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRNDrWouWBNdSzZ0XxtBB_77adQujZjx
"""

# !pip install unsloth --break-system-packages
# !pip install datasets pillow

from huggingface_hub import login
login(token="") # <- add token here 

from unsloth import FastVisionModel
import torch
from PIL import Image

model, tokenizer = FastVisionModel.from_pretrained(
    model_name = "aaryaupadhya20/rico-screen2words-qwen2.5_7B_VL",
    max_seq_length = 2048,
    load_in_4bit = True,
    dtype = torch.float16,
)

FastVisionModel.for_inference(model)

from unsloth import FastVisionModel
import torch

FastVisionModel.for_inference(model)

from datasets import load_dataset
from tqdm import tqdm

test_data = load_dataset("rootsautomation/RICO-Screen2Words", split="train")
test_data = test_data.shuffle(seed=99).select(range(10))

from PIL import Image

instruction = "You are a UI/UX expert. Describe what you see on this mobile app screen."

for i, sample in enumerate(tqdm(test_data)):
    try:
        image = sample["image"]
        ground_truth = sample["captions"][0]

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "text",  "text": instruction},
                    {"type": "image", "image": image},
                ]
            }
        ]

        input_text = tokenizer.apply_chat_template(
            messages,
            tokenize = False,
            add_generation_prompt = True,
        )

        inputs = tokenizer(
            image,
            input_text,
            add_special_tokens = False,
            return_tensors = "pt",
        ).to("cuda")

        inputs["pixel_values"] = inputs["pixel_values"].to(torch.float16)

        output_ids = model.generate(**inputs, max_new_tokens=128, use_cache=False)

        prediction = tokenizer.decode(output_ids[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
        print(f"Ground truth : {ground_truth}")
        print(f"Prediction   : {prediction}")

    except Exception as e:
        print(f"\n--- Sample {i+1} SKIPPED: {e} ---")
        continue

print(f"Ground truth : {ground_truth}")
print(f"Prediction   : {prediction}")